name: "AWS Static Site Build"

on:
  push:
    branches: ["main"]
    paths:
      - 'terraform/**'
      - '.github/workflows/tf-create.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    uses: rdavis542/aws-github-workflows/.github/workflows/tf-plan-apply.yml@main
    with:
      aws_region: us-east-1
      tf_vars: '{"region":"us-east-1","domain_name":"rdconsult.ing","site_name":"rdconsult-ing"}'
    secrets: inherit
